// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package org.some.thing.commons;

public final class Model {
  private Model() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IngessOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Ingess)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 time = 1;</code>
     */
    long getTime();

    /**
     * <code>optional string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>optional string property = 3;</code>
     */
    java.lang.String getProperty();
    /**
     * <code>optional string property = 3;</code>
     */
    com.google.protobuf.ByteString
        getPropertyBytes();
  }
  /**
   * Protobuf type {@code Ingess}
   */
  public  static final class Ingess extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Ingess)
      IngessOrBuilder {
    // Use Ingess.newBuilder() to construct.
    private Ingess(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ingess() {
      time_ = 0L;
      value_ = "";
      property_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Ingess(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              time_ = input.readUInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              property_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.some.thing.commons.Model.internal_static_Ingess_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.some.thing.commons.Model.internal_static_Ingess_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.some.thing.commons.Model.Ingess.class, org.some.thing.commons.Model.Ingess.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>optional uint64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>optional string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROPERTY_FIELD_NUMBER = 3;
    private volatile java.lang.Object property_;
    /**
     * <code>optional string property = 3;</code>
     */
    public java.lang.String getProperty() {
      java.lang.Object ref = property_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        property_ = s;
        return s;
      }
    }
    /**
     * <code>optional string property = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPropertyBytes() {
      java.lang.Object ref = property_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        property_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != 0L) {
        output.writeUInt64(1, time_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      if (!getPropertyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, property_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, time_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      if (!getPropertyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, property_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.some.thing.commons.Model.Ingess)) {
        return super.equals(obj);
      }
      org.some.thing.commons.Model.Ingess other = (org.some.thing.commons.Model.Ingess) obj;

      boolean result = true;
      result = result && (getTime()
          == other.getTime());
      result = result && getValue()
          .equals(other.getValue());
      result = result && getProperty()
          .equals(other.getProperty());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + PROPERTY_FIELD_NUMBER;
      hash = (53 * hash) + getProperty().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.some.thing.commons.Model.Ingess parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.some.thing.commons.Model.Ingess parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.some.thing.commons.Model.Ingess parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.some.thing.commons.Model.Ingess parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.some.thing.commons.Model.Ingess parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.some.thing.commons.Model.Ingess parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.some.thing.commons.Model.Ingess parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.some.thing.commons.Model.Ingess parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.some.thing.commons.Model.Ingess parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.some.thing.commons.Model.Ingess parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.some.thing.commons.Model.Ingess prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Ingess}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Ingess)
        org.some.thing.commons.Model.IngessOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.some.thing.commons.Model.internal_static_Ingess_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.some.thing.commons.Model.internal_static_Ingess_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.some.thing.commons.Model.Ingess.class, org.some.thing.commons.Model.Ingess.Builder.class);
      }

      // Construct using org.some.thing.commons.Model.Ingess.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        time_ = 0L;

        value_ = "";

        property_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.some.thing.commons.Model.internal_static_Ingess_descriptor;
      }

      public org.some.thing.commons.Model.Ingess getDefaultInstanceForType() {
        return org.some.thing.commons.Model.Ingess.getDefaultInstance();
      }

      public org.some.thing.commons.Model.Ingess build() {
        org.some.thing.commons.Model.Ingess result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.some.thing.commons.Model.Ingess buildPartial() {
        org.some.thing.commons.Model.Ingess result = new org.some.thing.commons.Model.Ingess(this);
        result.time_ = time_;
        result.value_ = value_;
        result.property_ = property_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.some.thing.commons.Model.Ingess) {
          return mergeFrom((org.some.thing.commons.Model.Ingess)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.some.thing.commons.Model.Ingess other) {
        if (other == org.some.thing.commons.Model.Ingess.getDefaultInstance()) return this;
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        if (!other.getProperty().isEmpty()) {
          property_ = other.property_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.some.thing.commons.Model.Ingess parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.some.thing.commons.Model.Ingess) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long time_ ;
      /**
       * <code>optional uint64 time = 1;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional uint64 time = 1;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 time = 1;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>optional string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object property_ = "";
      /**
       * <code>optional string property = 3;</code>
       */
      public java.lang.String getProperty() {
        java.lang.Object ref = property_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          property_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string property = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPropertyBytes() {
        java.lang.Object ref = property_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          property_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string property = 3;</code>
       */
      public Builder setProperty(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        property_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string property = 3;</code>
       */
      public Builder clearProperty() {
        
        property_ = getDefaultInstance().getProperty();
        onChanged();
        return this;
      }
      /**
       * <code>optional string property = 3;</code>
       */
      public Builder setPropertyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        property_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Ingess)
    }

    // @@protoc_insertion_point(class_scope:Ingess)
    private static final org.some.thing.commons.Model.Ingess DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.some.thing.commons.Model.Ingess();
    }

    public static org.some.thing.commons.Model.Ingess getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ingess>
        PARSER = new com.google.protobuf.AbstractParser<Ingess>() {
      public Ingess parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Ingess(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Ingess> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ingess> getParserForType() {
      return PARSER;
    }

    public org.some.thing.commons.Model.Ingess getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CardinalityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Cardinality)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 time = 1;</code>
     */
    long getTime();

    /**
     * <code>optional string property = 2;</code>
     */
    java.lang.String getProperty();
    /**
     * <code>optional string property = 2;</code>
     */
    com.google.protobuf.ByteString
        getPropertyBytes();

    /**
     * <code>optional string method = 3;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>optional string method = 3;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>optional uint64 window = 4;</code>
     */
    long getWindow();

    /**
     * <code>optional uint64 cardinality = 5;</code>
     */
    long getCardinality();

    /**
     * <code>optional double error = 6;</code>
     */
    double getError();
  }
  /**
   * Protobuf type {@code Cardinality}
   */
  public  static final class Cardinality extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Cardinality)
      CardinalityOrBuilder {
    // Use Cardinality.newBuilder() to construct.
    private Cardinality(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Cardinality() {
      time_ = 0L;
      property_ = "";
      method_ = "";
      window_ = 0L;
      cardinality_ = 0L;
      error_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Cardinality(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              time_ = input.readUInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              property_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            case 32: {

              window_ = input.readUInt64();
              break;
            }
            case 40: {

              cardinality_ = input.readUInt64();
              break;
            }
            case 49: {

              error_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.some.thing.commons.Model.internal_static_Cardinality_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.some.thing.commons.Model.internal_static_Cardinality_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.some.thing.commons.Model.Cardinality.class, org.some.thing.commons.Model.Cardinality.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>optional uint64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int PROPERTY_FIELD_NUMBER = 2;
    private volatile java.lang.Object property_;
    /**
     * <code>optional string property = 2;</code>
     */
    public java.lang.String getProperty() {
      java.lang.Object ref = property_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        property_ = s;
        return s;
      }
    }
    /**
     * <code>optional string property = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPropertyBytes() {
      java.lang.Object ref = property_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        property_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 3;
    private volatile java.lang.Object method_;
    /**
     * <code>optional string method = 3;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <code>optional string method = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WINDOW_FIELD_NUMBER = 4;
    private long window_;
    /**
     * <code>optional uint64 window = 4;</code>
     */
    public long getWindow() {
      return window_;
    }

    public static final int CARDINALITY_FIELD_NUMBER = 5;
    private long cardinality_;
    /**
     * <code>optional uint64 cardinality = 5;</code>
     */
    public long getCardinality() {
      return cardinality_;
    }

    public static final int ERROR_FIELD_NUMBER = 6;
    private double error_;
    /**
     * <code>optional double error = 6;</code>
     */
    public double getError() {
      return error_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != 0L) {
        output.writeUInt64(1, time_);
      }
      if (!getPropertyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, property_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, method_);
      }
      if (window_ != 0L) {
        output.writeUInt64(4, window_);
      }
      if (cardinality_ != 0L) {
        output.writeUInt64(5, cardinality_);
      }
      if (error_ != 0D) {
        output.writeDouble(6, error_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, time_);
      }
      if (!getPropertyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, property_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, method_);
      }
      if (window_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, window_);
      }
      if (cardinality_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, cardinality_);
      }
      if (error_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, error_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.some.thing.commons.Model.Cardinality)) {
        return super.equals(obj);
      }
      org.some.thing.commons.Model.Cardinality other = (org.some.thing.commons.Model.Cardinality) obj;

      boolean result = true;
      result = result && (getTime()
          == other.getTime());
      result = result && getProperty()
          .equals(other.getProperty());
      result = result && getMethod()
          .equals(other.getMethod());
      result = result && (getWindow()
          == other.getWindow());
      result = result && (getCardinality()
          == other.getCardinality());
      result = result && (
          java.lang.Double.doubleToLongBits(getError())
          == java.lang.Double.doubleToLongBits(
              other.getError()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + PROPERTY_FIELD_NUMBER;
      hash = (53 * hash) + getProperty().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      hash = (37 * hash) + WINDOW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getWindow());
      hash = (37 * hash) + CARDINALITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCardinality());
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getError()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.some.thing.commons.Model.Cardinality parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.some.thing.commons.Model.Cardinality parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.some.thing.commons.Model.Cardinality parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.some.thing.commons.Model.Cardinality parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.some.thing.commons.Model.Cardinality parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.some.thing.commons.Model.Cardinality parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.some.thing.commons.Model.Cardinality parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.some.thing.commons.Model.Cardinality parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.some.thing.commons.Model.Cardinality parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.some.thing.commons.Model.Cardinality parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.some.thing.commons.Model.Cardinality prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Cardinality}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Cardinality)
        org.some.thing.commons.Model.CardinalityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.some.thing.commons.Model.internal_static_Cardinality_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.some.thing.commons.Model.internal_static_Cardinality_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.some.thing.commons.Model.Cardinality.class, org.some.thing.commons.Model.Cardinality.Builder.class);
      }

      // Construct using org.some.thing.commons.Model.Cardinality.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        time_ = 0L;

        property_ = "";

        method_ = "";

        window_ = 0L;

        cardinality_ = 0L;

        error_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.some.thing.commons.Model.internal_static_Cardinality_descriptor;
      }

      public org.some.thing.commons.Model.Cardinality getDefaultInstanceForType() {
        return org.some.thing.commons.Model.Cardinality.getDefaultInstance();
      }

      public org.some.thing.commons.Model.Cardinality build() {
        org.some.thing.commons.Model.Cardinality result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.some.thing.commons.Model.Cardinality buildPartial() {
        org.some.thing.commons.Model.Cardinality result = new org.some.thing.commons.Model.Cardinality(this);
        result.time_ = time_;
        result.property_ = property_;
        result.method_ = method_;
        result.window_ = window_;
        result.cardinality_ = cardinality_;
        result.error_ = error_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.some.thing.commons.Model.Cardinality) {
          return mergeFrom((org.some.thing.commons.Model.Cardinality)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.some.thing.commons.Model.Cardinality other) {
        if (other == org.some.thing.commons.Model.Cardinality.getDefaultInstance()) return this;
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (!other.getProperty().isEmpty()) {
          property_ = other.property_;
          onChanged();
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        if (other.getWindow() != 0L) {
          setWindow(other.getWindow());
        }
        if (other.getCardinality() != 0L) {
          setCardinality(other.getCardinality());
        }
        if (other.getError() != 0D) {
          setError(other.getError());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.some.thing.commons.Model.Cardinality parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.some.thing.commons.Model.Cardinality) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long time_ ;
      /**
       * <code>optional uint64 time = 1;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional uint64 time = 1;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 time = 1;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object property_ = "";
      /**
       * <code>optional string property = 2;</code>
       */
      public java.lang.String getProperty() {
        java.lang.Object ref = property_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          property_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string property = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPropertyBytes() {
        java.lang.Object ref = property_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          property_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string property = 2;</code>
       */
      public Builder setProperty(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        property_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string property = 2;</code>
       */
      public Builder clearProperty() {
        
        property_ = getDefaultInstance().getProperty();
        onChanged();
        return this;
      }
      /**
       * <code>optional string property = 2;</code>
       */
      public Builder setPropertyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        property_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <code>optional string method = 3;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string method = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string method = 3;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 3;</code>
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 3;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }

      private long window_ ;
      /**
       * <code>optional uint64 window = 4;</code>
       */
      public long getWindow() {
        return window_;
      }
      /**
       * <code>optional uint64 window = 4;</code>
       */
      public Builder setWindow(long value) {
        
        window_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 window = 4;</code>
       */
      public Builder clearWindow() {
        
        window_ = 0L;
        onChanged();
        return this;
      }

      private long cardinality_ ;
      /**
       * <code>optional uint64 cardinality = 5;</code>
       */
      public long getCardinality() {
        return cardinality_;
      }
      /**
       * <code>optional uint64 cardinality = 5;</code>
       */
      public Builder setCardinality(long value) {
        
        cardinality_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 cardinality = 5;</code>
       */
      public Builder clearCardinality() {
        
        cardinality_ = 0L;
        onChanged();
        return this;
      }

      private double error_ ;
      /**
       * <code>optional double error = 6;</code>
       */
      public double getError() {
        return error_;
      }
      /**
       * <code>optional double error = 6;</code>
       */
      public Builder setError(double value) {
        
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double error = 6;</code>
       */
      public Builder clearError() {
        
        error_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Cardinality)
    }

    // @@protoc_insertion_point(class_scope:Cardinality)
    private static final org.some.thing.commons.Model.Cardinality DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.some.thing.commons.Model.Cardinality();
    }

    public static org.some.thing.commons.Model.Cardinality getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Cardinality>
        PARSER = new com.google.protobuf.AbstractParser<Cardinality>() {
      public Cardinality parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Cardinality(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Cardinality> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cardinality> getParserForType() {
      return PARSER;
    }

    public org.some.thing.commons.Model.Cardinality getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ingess_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ingess_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Cardinality_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Cardinality_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013model.proto\"7\n\006Ingess\022\014\n\004time\030\001 \001(\004\022\r\n" +
      "\005value\030\002 \001(\t\022\020\n\010property\030\003 \001(\t\"q\n\013Cardin" +
      "ality\022\014\n\004time\030\001 \001(\004\022\020\n\010property\030\002 \001(\t\022\016\n" +
      "\006method\030\003 \001(\t\022\016\n\006window\030\004 \001(\004\022\023\n\013cardina" +
      "lity\030\005 \001(\004\022\r\n\005error\030\006 \001(\001B\030\n\026org.some.th" +
      "ing.commonsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Ingess_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Ingess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ingess_descriptor,
        new java.lang.String[] { "Time", "Value", "Property", });
    internal_static_Cardinality_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Cardinality_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Cardinality_descriptor,
        new java.lang.String[] { "Time", "Property", "Method", "Window", "Cardinality", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
